site_name: 每日笔记
site_description: >-
    此网站用来每日记录日常工作中的零零散散的东西。
site_author: Orange
repo_url: https://gitee.com/orange19961/daily-notes
docs_dir: docs
site_dir: site
edit_uri: edit/master/docs
use_directory_urls: true
extra:
    generator: false
theme:
    name: readthedocs
    palette:
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/toggle-switch-off-outline
              name: 切换白天模式
          primary: cyan
          accent: yellow
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/toggle-switch
              name: 切换黑夜模式
          primary: indigo
          accent: deep purple
    language: en
    features:
        - navigation.instant
        - navigation.tracking
plugins:
    - search:
          lang: en

extra_css:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js

markdown_extensions:
    - attr_list
    - admonition
    - toc:
          permalink: true
          toc_depth: 3
